name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
    - name: Build and test with Rake
      run: |
        bundle install --jobs 4 --retry 3        
        bundle exec rake
